from embedia.layers.layer import Layer


class Pooling(Layer):
    """
    The Pooling layer is a layer that requires additional data beyond the input
    data. However, these values can be assigned directly to the additional data
    structure in its declaration. For this reason, it inherits from the "Layer"
    class that implements the basic behavior of an EmbedIA layer/element and
    not from the "DataLayer" class that implements an initialization function.
    This structure is declared as static in the before the invocation of the C
    function that implements the layer function.
    Normally, the programmer must implement the "predict" method, with the
    invocation to the EmbedIA function (previously implemented in "embedia.c")
    that performs the layer processing.
    This class encompasses the behavior of the pooling layers (Average, Max,
    etc.) and in principle it is not necessary to create subclasses for the
    implementation of each type. In particular it implements the
    "get_pool_name" method that uses an automatic naming rule from the name of
    the Keras pooling function for all pooling layers. The "predict" method
    invokes the C function (which must be defined in "embedia.h" and
    implemented in "embedia.c") using this name.
    Ex: For the pooling function named "avg_pool" for 2 dimensions, the C
    function named "avg_pooling2d_layer" will be called, composed by the first
    part of the name "avg" followed by "_pooling" + "input dimension" +
    "d_layer".
    """

    def __init__(self, model, layer, options=None, **kwargs):
        super().__init__(model, layer, options, **kwargs)

        self.dimensions = len(layer.pool_size)
        dim = self.dimensions

        # the input/output data types depends on the numbers of dimensions
        self.input_data_type = f'data{dim+1}d_t'
        self.output_data_type = f'data{dim+1}d_t'

        self.strides = layer.strides[0]
        self.pool_size = layer.pool_size[0]
        # These values must be redefined in the subclass if it does not follow
        # the automatic naming rule.
        (self.pool_name, self.struct_data_type) = self.get_pool_name(layer)

    def get_pool_name(self, layer):
        """
        Gets the name of the EmbedIA function to be invoked to perform the
        layer processing. The definition of the function with this name must
        be defined in "embedia.h" and implemented in "embedia.c".

        Parameters
        ----------
        layer : object
            Keras pooling layer object

        Returns
        -------
        str
            name of EmbedIA pooling function to call in predict method

        """
        name = layer.pool_function.__name__.lower()
        name = name[0:name.find('_')] + '_pooling%dd_layer' % self.dimensions
        data_type = 'pooling%dd_layer_t' % self.dimensions
        return  (name, data_type)

    def predict(self, input_name, output_name):
        """
        Generates C code for the invoke the EmbedIA function that implements
        the layer/element. The C function must be previously implemented in
        "embedia.c" and by convention should be called by the name
        autogenerated "get_pool_name" method.

        Parameters
        ----------
        input_name : str
            name of the input variable to be used in the invocation of the C
            function that implements the layer.
        output_name : str
            name of the output variable to be used in the invocation of the C
            function that implements the layer.

        Returns
        -------
        str
            C code with the invocation of the function that performs the
            processing of the layer in the file "embedia.c".

        """

        name = self.name
        pool_name = self.pool_name
        strides = self.strides
        pool_size = self.pool_size
        dim = self.dimensions
        text = f'''static const pooling{dim}d_layer_t {name}_data = {{ {pool_size}, {strides} }};
{pool_name}({name}_data, {input_name}, &{output_name});'''
        return text
