#ifndef _DECISION_TREE_H
#define _DECISION_TREE_H
/*
 * EmbedIA - Embedded Machine Learning and Neural Networks Framework
 * Copyright (c) 2022
 * César Estrebou & contributors
 * Instituto de Investigación en Informática LIDI (III-LIDI)
 * Facultad de Informática - Universidad Nacional de La Plata (UNLP)
 * Originally developed with student contributions
 *
 * Licensed under the BSD 3-Clause License. See LICENSE file for details.
 * GitHub: https://github.com/Embed-ML/EmbedIA
 */

#include <stdio.h>
#include <stdlib.h>

#include "common.h"

#ifdef __cplusplus
extern "C" {
#endif


/**
 * Maximum number of nodes in the tree.
 * This value is generated by the exporter.
 */
#define DTREE_MAX_NODES 128

/**
 * Number of input features expected by the model.
 */
#define DTREE_N_FEATURES 12

/**
 * Number of classes predicted by the model.
 */
#define DTREE_N_CLASSES 3


/* Definition of types used in the decision tree implementation. */

/* Node index type depends on the maximum number of nodes */

#if DTREE_MAX_NODES < 255
    typedef uint8_t node_index_t;
#else
    typedef uint16_t node_index_t;
#endif


/* Feature index type depends on the number of input features */

#if DTREE_N_FEATURES <= 255
    typedef uint8_t feature_id_t;
    #define DT_LEAF_NODE ((feature_id_t)0xFF)
#else
    typedef uint16_t feature_id_t;
    #define DT_LEAF_NODE ((feature_id_t)0xFFFF)
#endif


/* Class identifier type depends on the number of classes */

#if DTREE_N_CLASSES <= 255
    typedef uint8_t class_id_t;
#else
    typedef uint16_t class_id_t;
#endif

/**
 * Check if a node is a leaf node.
 */
#define DT_IS_LEAF(node) ((node).feature_id == DT_LEAF_NODE)


/**
 * Node structure for CART decision tree.
 *
 * Each node stores explicit indices for the left and right children.
 * Leaf nodes are identified using DT_LEAF_NODE in feature_id.
 */
typedef struct {
    storage_t threshold;        /* Threshold value for the comparison */
    feature_id_t feature_id;    /* Feature index used for the split */
    node_index_t right_offset;  /* Index of the right child, left child is current node + 1 */
    class_id_t value;           /* Class ID returned when the node is a leaf */
} Node;


/**
 * Decision tree classifier layer.
 */
typedef struct
{
    uint16_t n_features;                // Number of input features
    uint16_t n_classes;                 // Number of output classes
    EMBEDIA_MODEL_STORAGE Node *nodes;  // Array of tree nodes
} decision_tree_classifier_layer_t;


void decision_tree_classifier_layer(decision_tree_classifier_layer_t tree, data1d_t input, data1d_t* output);

#ifdef __cplusplus
}
#endif

#endif


